theme = "casper"
baseurl = "http://reedmurphy.net/"
languageCode = "en-us"
title = "/Reed( Kraft-)?Murphy(\\.net)?/"
copyright = "© 2015 Reed Kraft-Murphy"
DisqusShortname = "reedmurphy"
PygmentsCodeFences = true

[Params]
googleAnalyticsUserID = "UA-25443368-1"
description = "the ramblings of a devops engineer and polymath"
cover = "/img/quarternion.png"
author = "Reed Kraft-Murphy"
githubName = "RWJMurphy"
linkedinName = "reedkraftmurphy"
twitterName = "RWJKM"
paginate = 10
dateform = "Mon, Jan 2, 2006"
dateformat = "Mon, Jan 2, 2006"

[[menu.main]]
name = "Blog"
weight = 0
identifier = "blog"
url = "/#content"

[[menu.main]]
name = "About"
weight = 10
identifier = "about"
url = "/page/about"

[[menu.main]]
name = "Resume"
weight = 20
identifier = "resume"
url = "/page/resume"

[[menu.main]]
name = "Privacy"
weight = 100
identifier = "privacy"
url = "/page/privacy"
